In [2]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international"

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [3]:
data

{'seriesMapProto': [{'date': 'FEBRUARY 2024',
   'series': [{'id': 7572,
     'name': 'ICC Cricket World Cup League Two 2023-27',
     'startDt': '1707955200000',
     'endDt': '1806364800000'}]},
  {'date': 'AUGUST 2025',
   'series': [{'id': 9686,
     'name': 'India tour of Bangladesh, 2025 (Called off)',
     'startDt': '1755388800000',
     'endDt': '1756598400000'},
    {'id': 10790,
     'name': 'Eastern Europe Cup 2025',
     'startDt': '1756425600000',
     'endDt': '1756598400000'},
    {'id': 10267,
     'name': 'Sri Lanka tour of Zimbabwe, 2025',
     'startDt': '1756425600000',
     'endDt': '1757203200000'},
    {'id': 10642,
     'name': 'United Arab Emirates T20I Tri-Series 2025',
     'startDt': '1756425600000',
     'endDt': '1757203200000'},
    {'id': 10801,
     'name': 'Switzerland tour of Guernsey, 2025',
     'startDt': '1756512000000',
     'endDt': '1756598400000'},
    {'id': 10647,
     'name': 'Netherlands tour of Bangladesh 2025',
     'startDt': '1756512000000',
     'endDt': '1756857600000'}]},
  {'date': 'SEPTEMBER 2025',
   'series': [{'id': 8788,
     'name': 'South Africa tour of England, 2025',
     'startDt': '1756771200000',
     'endDt': '1757808000000'},
    {'id': 10812,
     'name': 'Sweden tour of Isle Of Man 2025',
     'startDt': '1757116800000',
     'endDt': '1757203200000'},
    {'id': 10587,
     'name': 'Asia Cup 2025',
     'startDt': '1757376000000',
     'endDt': '1759017600000'},
    {'id': 8802,
     'name': 'England tour of Ireland, 2025',
     'startDt': '1758067200000',
     'endDt': '1758412800000'},
    {'id': 10091,
     'name': 'West Indies vs Nepal in UAE, 2025',
     'startDt': '1758931200000',
     'endDt': '1759190400000'},
    {'id': 10201,
     'name': 'Australia tour of New Zealand, 2025',
     'startDt': '1759276800000',
     'endDt': '1759536000000'}]},
  {'date': 'OCTOBER 2025',
   'series': [{'id': 9629,
     'name': 'West Indies tour of India, 2025',
     'startDt': '1759363200000',
     'endDt': '1760400000000'},
    {'id': 10840,
     'name': 'Afghanistan vs Bangladesh in UAE 2025',
     'startDt': '1759363200000',
     'endDt': '1760400000000'},
    {'id': 10625,
     'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier 2025',
     'startDt': '1759881600000',
     'endDt': '1760659200000'},
    {'id': 10504,
     'name': 'South Africa tour of Namibia 2025',
     'startDt': '1760140800000',
     'endDt': '1760140800000'},
    {'id': 10212,
     'name': 'England tour of New Zealand, 2025',
     'startDt': '1760745600000',
     'endDt': '1761955200000'},
    {'id': 9596,
     'name': 'India tour of Australia, 2025',
     'startDt': '1760832000000',
     'endDt': '1762560000000'}]},
  {'date': 'NOVEMBER 2025',
   'series': [{'id': 10223,
     'name': 'West Indies tour of New Zealand, 2025',
     'startDt': '1762300800000',
     'endDt': '1766361600000'},
    {'id': 9638,
     'name': 'South Africa tour of India, 2025',
     'startDt': '1763078400000',
     'endDt': '1766102400000'},
    {'id': 9107,
     'name': 'The Ashes, 2025-26',
     'startDt': '1763683200000',
     'endDt': '1767830400000'}]},
  {'date': 'JANUARY 2026',
   'series': [{'id': 10102,
     'name': 'New Zealand tour of India, 2026',
     'startDt': '1768089600000',
     'endDt': '1769817600000'},
    {'id': 10774,
     'name': 'England tour of Sri Lanka 2026',
     'startDt': '1769040000000',
     'endDt': '1770076800000'},
    {'id': 9551,
     'name': 'West Indies tour of South Africa, 2026',
     'startDt': '1769472000000',
     'endDt': '1770336000000'}]},
  {'date': 'MARCH 2026',
   'series': [{'id': 10234,
     'name': 'South Africa tour of New Zealand, 2026',
     'startDt': '1773532800000',
     'endDt': '1774396800000'}]},
  {'date': 'JUNE 2026',
   'series': [{'id': 10559,
     'name': 'New Zealand tour of England, 2026',
     'startDt': '1780531200000',
     'endDt': '1782691200000'},
    {'id': 10532,
     'name': 'India tour of England, 2026',
     'startDt': '1782864000000',
     'endDt': '1784419200000'}]},
  {'date': 'AUGUST 2026',
   'series': [{'id': 10565,
     'name': 'Pakistan tour of England 2026',
     'startDt': '1787097600000',
     'endDt': '1788912000000'}]},
  {'date': 'SEPTEMBER 2026',
   'series': [{'id': 10576,
     'name': 'Sri Lanka tour of England, 2026',
     'startDt': '1789430400000',
     'endDt': '1790467200000'}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [4]:
# Check if 'seriesMapProto' exists and is a list
if 'seriesMapProto' in data and isinstance(data['seriesMapProto'], list):
    matches = data['seriesMapProto']
    print("Length of seriesMapProto:", len(matches))  # Check the length of the 'seriesMapProto' list
    
    # Loop through the matches and extract relevant details
    for match in matches:  # Directly iterate over the list items (no need for .items())
        # Add a new line before each match's record for better readability
        print("\n--- New Match Record ---")
        
        match_date = match['date']
        series = match['series']
        
        # Assuming series is a list and we are accessing the first series
        series_id = series[0]['id']
        series_name = series[0]['name']
        series_startdate = series[0]['startDt']
        series_enddate = series[0]['endDt']
        
        # Print the extracted details
        print(f"Match Date: {match_date}")
        print(f"Series ID: {series_id}")
        print(f"Series Name: {series_name}")
        print(f"Series Start Date: {series_startdate}")
        print(f"Series End Date: {series_enddate}")
else:
    print("Key 'seriesMapProto' not found or not a list in data.")

Length of seriesMapProto: 10

--- New Match Record ---
Match Date: FEBRUARY 2024
Series ID: 7572
Series Name: ICC Cricket World Cup League Two 2023-27
Series Start Date: 1707955200000
Series End Date: 1806364800000

--- New Match Record ---
Match Date: AUGUST 2025
Series ID: 9686
Series Name: India tour of Bangladesh, 2025 (Called off)
Series Start Date: 1755388800000
Series End Date: 1756598400000

--- New Match Record ---
Match Date: SEPTEMBER 2025
Series ID: 8788
Series Name: South Africa tour of England, 2025
Series Start Date: 1756771200000
Series End Date: 1757808000000

--- New Match Record ---
Match Date: OCTOBER 2025
Series ID: 9629
Series Name: West Indies tour of India, 2025
Series Start Date: 1759363200000
Series End Date: 1760400000000

--- New Match Record ---
Match Date: NOVEMBER 2025
Series ID: 10223
Series Name: West Indies tour of New Zealand, 2025
Series Start Date: 1762300800000
Series End Date: 1766361600000

--- New Match Record ---
Match Date: JANUARY 2026
Series ID: 10102
Series Name: New Zealand tour of India, 2026
Series Start Date: 1768089600000
Series End Date: 1769817600000

--- New Match Record ---
Match Date: MARCH 2026
Series ID: 10234
Series Name: South Africa tour of New Zealand, 2026
Series Start Date: 1773532800000
Series End Date: 1774396800000

--- New Match Record ---
Match Date: JUNE 2026
Series ID: 10559
Series Name: New Zealand tour of England, 2026
Series Start Date: 1780531200000
Series End Date: 1782691200000

--- New Match Record ---
Match Date: AUGUST 2026
Series ID: 10565
Series Name: Pakistan tour of England 2026
Series Start Date: 1787097600000
Series End Date: 1788912000000

--- New Match Record ---
Match Date: SEPTEMBER 2026
Series ID: 10576
Series Name: Sri Lanka tour of England, 2026
Series Start Date: 1789430400000
Series End Date: 1790467200000

In [ ]:
from db_connection import get_db_connection
from pymysql import Error
import datetime

# Function to insert match data into the MySQL table
def insert_match_data(connection, match_data):
    cursor = connection.cursor()
    
    # SQL query to insert match details into the live_matches table
    insert_query = """
    INSERT INTO live_matches (match_date, series_id, series_name, series_startdate, series_enddate)
    VALUES (%s, %s, %s, %s, %s)
    """
    
    try:
        # Executing the query with the match details
        cursor.execute(insert_query, match_data)
        connection.commit()  # Commit the transaction
        print(f"Match inserted successfully!")
    except Error as e:
        print(f"Error while inserting match data: {e}")
        connection.rollback()  # Rollback in case of an error

# Main code to extract and insert data into MySQL
if 'seriesMapProto' in data and isinstance(data['seriesMapProto'], list):
    matches = data['seriesMapProto']
    connection = get_db_connection()  # Get the database connection from the imported function

    if connection:
        # Loop through the matches and insert into the database
        for match in matches:
            match_date = match['date']  # Keep match_date as a string
            series = match['series']
            
            # Assuming series is a list and we are accessing the first series
            series_id = series[0]['id']
            series_name = series[0]['name']
            series_startdate = series[0]['startDt']
            series_enddate = series[0]['endDt']
            
            # Prepare data tuple for inserting into the database
            match_data = (match_date, series_id, series_name, series_startdate, series_enddate)
            
            # Insert the match data into the MySQL table
            insert_match_data(connection, match_data)

        connection.close()  # Close the database connection
    else:
        print("Failed to connect to the database.")
else:
    print("Key 'seriesMapProto' not found or not a list in data.")

Error while inserting match data: (1292, "Incorrect date value: '1707955200000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1755388800000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1756771200000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1759363200000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1762300800000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1768089600000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1773532800000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1780531200000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1787097600000' for column 'series_startdate' at row 1")
Error while inserting match data: (1292, "Incorrect date value: '1789430400000' for column 'series_startdate' at row 1")

In [6]:
from db_connection import get_db_connection
import pymysql
from pymysql import Error
from datetime import datetime, timezone

# Function to convert timestamp (in milliseconds) to a date string (YYYY-MM-DD)
def convert_timestamp_to_date(timestamp):
    # Convert the timestamp to seconds
    timestamp_in_seconds = int(timestamp) / 1000
    # Convert to a datetime object in UTC and format as 'YYYY-MM-DD'
    return datetime.fromtimestamp(timestamp_in_seconds, tz=timezone.utc).strftime('%Y-%m-%d')

# Function to insert match data into the MySQL table
def insert_match_data(connection, match_data):
    cursor = connection.cursor()
    
    # SQL query to insert match details into the live_matches table
    insert_query = """
    INSERT INTO live_matches (match_date, series_id, series_name, series_startdate, series_enddate)
    VALUES (%s, %s, %s, %s, %s)
    """
    
    try:
        # Executing the query with the match details
        cursor.execute(insert_query, match_data)
        connection.commit()  # Commit the transaction
        print(f"Match inserted successfully!")
    except Error as e:
        print(f"Error while inserting match data: {e}")
        connection.rollback()  # Rollback in case of an error

# Main code to extract and insert data into MySQL
if 'seriesMapProto' in data and isinstance(data['seriesMapProto'], list):
    matches = data['seriesMapProto']
    connection = get_db_connection()  # Get the database connection from the imported function

    if connection:
        # Loop through the matches and insert into the database
        for match in matches:
            match_date = match['date']  # Keep match_date as a string
            series = match['series']
            
            # Assuming series is a list and we are accessing the first series
            series_id = series[0]['id']
            series_name = series[0]['name']
            series_startdate = convert_timestamp_to_date(series[0]['startDt'])  # Convert timestamp to date
            series_enddate = convert_timestamp_to_date(series[0]['endDt'])      # Convert timestamp to date
            
            # Prepare data tuple for inserting into the database
            match_data = (match_date, series_id, series_name, series_startdate, series_enddate)
            
            # Insert the match data into the MySQL table
            insert_match_data(connection, match_data)

        connection.close()  # Close the database connection
    else:
        print("Failed to connect to the database.")
else:
    print("Key 'seriesMapProto' not found or not a list in data.")

Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!

In [7]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international"

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

date =response.json()

In [8]:
data

{'seriesMapProto': [{'date': 'FEBRUARY 2024',
   'series': [{'id': 7572,
     'name': 'ICC Cricket World Cup League Two 2023-27',
     'startDt': '1707955200000',
     'endDt': '1806364800000'}]},
  {'date': 'AUGUST 2025',
   'series': [{'id': 9686,
     'name': 'India tour of Bangladesh, 2025 (Called off)',
     'startDt': '1755388800000',
     'endDt': '1756598400000'},
    {'id': 10790,
     'name': 'Eastern Europe Cup 2025',
     'startDt': '1756425600000',
     'endDt': '1756598400000'},
    {'id': 10267,
     'name': 'Sri Lanka tour of Zimbabwe, 2025',
     'startDt': '1756425600000',
     'endDt': '1757203200000'},
    {'id': 10642,
     'name': 'United Arab Emirates T20I Tri-Series 2025',
     'startDt': '1756425600000',
     'endDt': '1757203200000'},
    {'id': 10801,
     'name': 'Switzerland tour of Guernsey, 2025',
     'startDt': '1756512000000',
     'endDt': '1756598400000'},
    {'id': 10647,
     'name': 'Netherlands tour of Bangladesh 2025',
     'startDt': '1756512000000',
     'endDt': '1756857600000'}]},
  {'date': 'SEPTEMBER 2025',
   'series': [{'id': 8788,
     'name': 'South Africa tour of England, 2025',
     'startDt': '1756771200000',
     'endDt': '1757808000000'},
    {'id': 10812,
     'name': 'Sweden tour of Isle Of Man 2025',
     'startDt': '1757116800000',
     'endDt': '1757203200000'},
    {'id': 10587,
     'name': 'Asia Cup 2025',
     'startDt': '1757376000000',
     'endDt': '1759017600000'},
    {'id': 8802,
     'name': 'England tour of Ireland, 2025',
     'startDt': '1758067200000',
     'endDt': '1758412800000'},
    {'id': 10091,
     'name': 'West Indies vs Nepal in UAE, 2025',
     'startDt': '1758931200000',
     'endDt': '1759190400000'},
    {'id': 10201,
     'name': 'Australia tour of New Zealand, 2025',
     'startDt': '1759276800000',
     'endDt': '1759536000000'}]},
  {'date': 'OCTOBER 2025',
   'series': [{'id': 9629,
     'name': 'West Indies tour of India, 2025',
     'startDt': '1759363200000',
     'endDt': '1760400000000'},
    {'id': 10840,
     'name': 'Afghanistan vs Bangladesh in UAE 2025',
     'startDt': '1759363200000',
     'endDt': '1760400000000'},
    {'id': 10625,
     'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier 2025',
     'startDt': '1759881600000',
     'endDt': '1760659200000'},
    {'id': 10504,
     'name': 'South Africa tour of Namibia 2025',
     'startDt': '1760140800000',
     'endDt': '1760140800000'},
    {'id': 10212,
     'name': 'England tour of New Zealand, 2025',
     'startDt': '1760745600000',
     'endDt': '1761955200000'},
    {'id': 9596,
     'name': 'India tour of Australia, 2025',
     'startDt': '1760832000000',
     'endDt': '1762560000000'}]},
  {'date': 'NOVEMBER 2025',
   'series': [{'id': 10223,
     'name': 'West Indies tour of New Zealand, 2025',
     'startDt': '1762300800000',
     'endDt': '1766361600000'},
    {'id': 9638,
     'name': 'South Africa tour of India, 2025',
     'startDt': '1763078400000',
     'endDt': '1766102400000'},
    {'id': 9107,
     'name': 'The Ashes, 2025-26',
     'startDt': '1763683200000',
     'endDt': '1767830400000'}]},
  {'date': 'JANUARY 2026',
   'series': [{'id': 10102,
     'name': 'New Zealand tour of India, 2026',
     'startDt': '1768089600000',
     'endDt': '1769817600000'},
    {'id': 10774,
     'name': 'England tour of Sri Lanka 2026',
     'startDt': '1769040000000',
     'endDt': '1770076800000'},
    {'id': 9551,
     'name': 'West Indies tour of South Africa, 2026',
     'startDt': '1769472000000',
     'endDt': '1770336000000'}]},
  {'date': 'MARCH 2026',
   'series': [{'id': 10234,
     'name': 'South Africa tour of New Zealand, 2026',
     'startDt': '1773532800000',
     'endDt': '1774396800000'}]},
  {'date': 'JUNE 2026',
   'series': [{'id': 10559,
     'name': 'New Zealand tour of England, 2026',
     'startDt': '1780531200000',
     'endDt': '1782691200000'},
    {'id': 10532,
     'name': 'India tour of England, 2026',
     'startDt': '1782864000000',
     'endDt': '1784419200000'}]},
  {'date': 'AUGUST 2026',
   'series': [{'id': 10565,
     'name': 'Pakistan tour of England 2026',
     'startDt': '1787097600000',
     'endDt': '1788912000000'}]},
  {'date': 'SEPTEMBER 2026',
   'series': [{'id': 10576,
     'name': 'Sri Lanka tour of England, 2026',
     'startDt': '1789430400000',
     'endDt': '1790467200000'}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [10]:
# Check if 'seriesMapProto' exists and is a list
if 'seriesMapProto' in data and isinstance(data['seriesMapProto'], list):
    matches = data['seriesMapProto']
    print("Length of seriesMapProto:", len(matches))  # Check the length of the 'seriesMapProto' list
    
    # Loop through the matches and extract relevant details
    for match in matches:  # Directly iterate over the list items (no need for .items())
        # Add a new line before each match's record for better readability
        print("\n--- New Match Record ---")
        
        match_date = match['date']
        series = match['series']
        
        # Assuming series is a list and we are accessing the first series
        series_id = series[0]['id']
        series_name = series[0]['name']
        series_startdate = series[0]['startDt']
        series_enddate = series[0]['endDt']
        
        # Print the extracted details
        print(f"Match Date: {match_date}")
        print(f"Series ID: {series_id}")
        print(f"Series Name: {series_name}")
        print(f"Series Start Date: {series_startdate}")
        print(f"Series End Date: {series_enddate}")
else:
    print("Key 'seriesMapProto' not found or not a list in data.")

Length of seriesMapProto: 10

--- New Match Record ---
Match Date: FEBRUARY 2024
Series ID: 7572
Series Name: ICC Cricket World Cup League Two 2023-27
Series Start Date: 1707955200000
Series End Date: 1806364800000

--- New Match Record ---
Match Date: AUGUST 2025
Series ID: 9686
Series Name: India tour of Bangladesh, 2025 (Called off)
Series Start Date: 1755388800000
Series End Date: 1756598400000

--- New Match Record ---
Match Date: SEPTEMBER 2025
Series ID: 8788
Series Name: South Africa tour of England, 2025
Series Start Date: 1756771200000
Series End Date: 1757808000000

--- New Match Record ---
Match Date: OCTOBER 2025
Series ID: 9629
Series Name: West Indies tour of India, 2025
Series Start Date: 1759363200000
Series End Date: 1760400000000

--- New Match Record ---
Match Date: NOVEMBER 2025
Series ID: 10223
Series Name: West Indies tour of New Zealand, 2025
Series Start Date: 1762300800000
Series End Date: 1766361600000

--- New Match Record ---
Match Date: JANUARY 2026
Series ID: 10102
Series Name: New Zealand tour of India, 2026
Series Start Date: 1768089600000
Series End Date: 1769817600000

--- New Match Record ---
Match Date: MARCH 2026
Series ID: 10234
Series Name: South Africa tour of New Zealand, 2026
Series Start Date: 1773532800000
Series End Date: 1774396800000

--- New Match Record ---
Match Date: JUNE 2026
Series ID: 10559
Series Name: New Zealand tour of England, 2026
Series Start Date: 1780531200000
Series End Date: 1782691200000

--- New Match Record ---
Match Date: AUGUST 2026
Series ID: 10565
Series Name: Pakistan tour of England 2026
Series Start Date: 1787097600000
Series End Date: 1788912000000

--- New Match Record ---
Match Date: SEPTEMBER 2026
Series ID: 10576
Series Name: Sri Lanka tour of England, 2026
Series Start Date: 1789430400000
Series End Date: 1790467200000

In [11]:
from db_connection import get_db_connection
import pymysql
from pymysql import Error
from datetime import datetime, timezone

# Function to convert timestamp (in milliseconds) to a date string (YYYY-MM-DD)
def convert_timestamp_to_date(timestamp):
    # Convert the timestamp to seconds
    timestamp_in_seconds = int(timestamp) / 1000
    # Convert to a datetime object in UTC and format as 'YYYY-MM-DD'
    return datetime.fromtimestamp(timestamp_in_seconds, tz=timezone.utc).strftime('%Y-%m-%d')

# Function to insert match data into the MySQL table
def insert_match_data(connection, match_data):
    cursor = connection.cursor()
    
    # SQL query to insert match details into the live_matches table
    insert_query = """
    INSERT INTO series_list (match_date, series_id, series_name, series_startdate, series_enddate)
    VALUES (%s, %s, %s, %s, %s)
    """
    
    try:
        # Executing the query with the match details
        cursor.execute(insert_query, match_data)
        connection.commit()  # Commit the transaction
        print(f"Match inserted successfully!")
    except Error as e:
        print(f"Error while inserting match data: {e}")
        connection.rollback()  # Rollback in case of an error

# Main code to extract and insert data into MySQL
if 'seriesMapProto' in data and isinstance(data['seriesMapProto'], list):
    matches = data['seriesMapProto']
    connection = get_db_connection()  # Get the database connection from the imported function

    if connection:
        # Loop through the matches and insert into the database
        for match in matches:
            match_date = match['date']  # Keep match_date as a string
            series = match['series']
            
            # Assuming series is a list and we are accessing the first series
            series_id = series[0]['id']
            series_name = series[0]['name']
            series_startdate = convert_timestamp_to_date(series[0]['startDt'])  # Convert timestamp to date
            series_enddate = convert_timestamp_to_date(series[0]['endDt'])      # Convert timestamp to date
            
            # Prepare data tuple for inserting into the database
            match_data = (match_date, series_id, series_name, series_startdate, series_enddate)
            
            # Insert the match data into the MySQL table
            insert_match_data(connection, match_data)

        connection.close()  # Close the database connection
    else:
        print("Failed to connect to the database.")
else:
    print("Key 'seriesMapProto' not found or not a list in data.")

Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!
Match inserted successfully!

In [3]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/3641"

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data =response.json()

In [4]:
data

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 20 May 2022 - Mon, 23 May 2022',
    'match': [{'matchInfo': {'matchId': 48002,
       'seriesId': 3641,
       'seriesName': 'New Zealand tour of England, 2022',
       'matchDesc': '1st Warm-up Match',
       'matchFormat': 'TEST',
       'startDate': '1653040800000',
       'endDate': '1653300000000',
       'state': 'complete',
       'status': 'Match drawn',
       'team1': {'teamId': 41,
        'teamName': 'SUSSEX',
        'teamSName': 'SUS',
        'imageId': 172148},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 172128},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Hove',
        'timezone': '+01:00'},
       'currBatTeamId': 13,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 247,
         'wickets': 10,
         'overs': 79.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 342,
         'wickets': 3,
         'overs': 90.0,
         'isDeclared': True},
        'inngs2': {'inningsId': 3, 'runs': 40, 'overs': 8.0}}}}],
    'seriesId': 3641}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Thu, 26 May 2022 - Sun, 29 May 2022',
    'match': [{'matchInfo': {'matchId': 48009,
       'seriesId': 3641,
       'seriesName': 'New Zealand tour of England, 2022',
       'matchDesc': '2nd Warm-up Match',
       'matchFormat': 'TEST',
       'startDate': '1653559200000',
       'endDate': '1653818400000',
       'state': 'complete',
       'status': 'County Select XI won by 7 wkts',
       'team1': {'teamId': 886,
        'teamName': 'PROFESSIONAL COUNTY CLUB SELECT XI',
        'teamSName': 'PCCSXI',
        'imageId': 174284},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 172128},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Chelmsford',
        'timezone': '+01:00'},
       'currBatTeamId': 886,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 247,
         'wickets': 10,
         'overs': 74.2},
        'inngs2': {'inningsId': 4, 'runs': 264, 'wickets': 3, 'overs': 88.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 362,
         'wickets': 9,
         'overs': 100.0,
         'isDeclared': True},
        'inngs2': {'inningsId': 3,
         'runs': 148,
         'wickets': 10,
         'overs': 43.2}}}}],
    'seriesId': 3641}},
  {'matchDetailsMap': {'key': 'Thu, 02 Jun 2022 - Mon, 06 Jun 2022',
    'match': [{'matchInfo': {'matchId': 38326,
       'seriesId': 3641,
       'seriesName': 'New Zealand tour of England, 2022',
       'matchDesc': '1st Test',
       'matchFormat': 'TEST',
       'startDate': '1654164000000',
       'endDate': '1654509600000',
       'state': 'complete',
       'status': 'England won by 5 wkts',
       'team1': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 172123},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 172128},
       'venueInfo': {'ground': "Lord's",
        'city': 'London',
        'timezone': '+01:00'},
       'currBatTeamId': 9,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 141,
         'wickets': 10,
         'overs': 42.5},
        'inngs2': {'inningsId': 4, 'runs': 279, 'wickets': 5, 'overs': 78.5}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 132,
         'wickets': 10,
         'overs': 40.0},
        'inngs2': {'inningsId': 3,
         'runs': 285,
         'wickets': 10,
         'overs': 91.3}}}}],
    'seriesId': 3641}},
  {'matchDetailsMap': {'key': 'Fri, 10 Jun 2022 - Tue, 14 Jun 2022',
    'match': [{'matchInfo': {'matchId': 38331,
       'seriesId': 3641,
       'seriesName': 'New Zealand tour of England, 2022',
       'matchDesc': '2nd Test',
       'matchFormat': 'TEST',
       'startDate': '1654855200000',
       'endDate': '1655200800000',
       'state': 'complete',
       'status': 'England won by 5 wkts',
       'team1': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 172123},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 172128},
       'venueInfo': {'ground': 'Trent Bridge',
        'city': 'Nottingham',
        'timezone': '+01:00'},
       'currBatTeamId': 9,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 539,
         'wickets': 10,
         'overs': 128.2},
        'inngs2': {'inningsId': 4, 'runs': 299, 'wickets': 5, 'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 553,
         'wickets': 10,
         'overs': 145.3},
        'inngs2': {'inningsId': 3,
         'runs': 284,
         'wickets': 10,
         'overs': 84.4}}}}],
    'seriesId': 3641}},
  {'adDetail': {'name': 'native_news_index_random_2',
    'layout': 'native_large',
    'position': 4}},
  {'matchDetailsMap': {'key': 'Thu, 23 Jun 2022 - Mon, 27 Jun 2022',
    'match': [{'matchInfo': {'matchId': 38332,
       'seriesId': 3641,
       'seriesName': 'New Zealand tour of England, 2022',
       'matchDesc': '3rd Test',
       'matchFormat': 'TEST',
       'startDate': '1655978400000',
       'endDate': '1656324000000',
       'state': 'complete',
       'status': 'England won by 7 wkts',
       'team1': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 172123},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 172128},
       'venueInfo': {'ground': 'Headingley',
        'city': 'Leeds',
        'timezone': '+01:00'},
       'currBatTeamId': 9,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 360,
         'wickets': 10,
         'overs': 67.0},
        'inngs2': {'inningsId': 4, 'runs': 296, 'wickets': 3, 'overs': 54.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 329,
         'wickets': 10,
         'overs': 117.3},
        'inngs2': {'inningsId': 3,
         'runs': 326,
         'wickets': 10,
         'overs': 105.2}}}}],
    'seriesId': 3641}}],
 'appIndex': {'seoTitle': 'New Zealand tour of England, 2022 live scores, schedule and results - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [6]:
data['matchDetails'][0]['matchDetailsMap'].keys()
match_details = data['matchDetails'][0]['matchDetailsMap']
# series_id = data['matchDetails'][0]['matchDetailsMap']['seriesId']
matches = data['matchDetails'][0]['matchDetailsMap']['match']
matches 

series_id = matches[0]['matchInfo']['seriesId']
match_id = matches[0]['matchInfo']['matchId']
match_descriptions = matches[0]['matchInfo']['matchDesc']
match_format = matches[0]['matchInfo']['matchFormat']
match_status = matches[0]['matchInfo']['status']
team1_id = matches[0]['matchInfo']['team1']['teamId']
team1_name = matches[0]['matchInfo']['team1']['teamName']
team1_runs = matches[0]['matchScore']['team1Score']['inngs1']['runs']
team1_wickets = matches[0]['matchScore']['team1Score']['inngs1']['wickets']
team1_overs =  matches[0]['matchScore']['team1Score']['inngs1']['overs']
team2_id = matches[0]['matchInfo']['team2']['teamId']
team2_name = matches[0]['matchInfo']['team2']['teamName']
team2_runs = matches[0]['matchScore']['team2Score']['inngs1']['runs']
team2_wickets = matches[0]['matchScore']['team2Score']['inngs1']['wickets']
team2_overs =  matches[0]['matchScore']['team2Score']['inngs1']['overs']
venue = matches[0]['matchInfo']['venueInfo']['ground']
batting_teamId = matches[0]['matchInfo']['currBatTeamId']

score = matches[0]['matchScore']['team2Score']['inngs1']

In [7]:
match_details_map = data['matchDetails'][0]['matchDetailsMap']
match_data = match_details_map['match'][0]

# Extract general match info
series_id = match_data['matchInfo']['seriesId']
match_id = match_data['matchInfo']['matchId']
match_descriptions = match_data['matchInfo']['matchDesc']
match_format = match_data['matchInfo']['matchFormat']
match_status = match_data['matchInfo']['status']
venue = match_data['matchInfo']['venueInfo']['ground']
batting_team_id = match_data['matchInfo']['currBatTeamId']

# Extract Team 1 info
team1_id = match_data['matchInfo']['team1']['teamId']
team1_name = match_data['matchInfo']['team1']['teamName']

# Extract Team 1's scores with checks for missing keys
team1_inngs1_score = match_data['matchScore']['team1Score']['inngs1']
team1_inngs1_runs = team1_inngs1_score.get('runs', 'N/A')
team1_inngs1_wickets = team1_inngs1_score.get('wickets', 'Declared')
team1_inngs1_overs = team1_inngs1_score.get('overs', 'N/A')

team1_inngs2_score = match_data['matchScore']['team1Score'].get('inngs2')
if team1_inngs2_score:
    team1_inngs2_runs = team1_inngs2_score.get('runs', 'N/A')
    team1_inngs2_wickets = team1_inngs2_score.get('wickets', 'Declared')
    team1_inngs2_overs = team1_inngs2_score.get('overs', 'N/A')
else:
    team1_inngs2_runs = 'N/A'
    team1_inngs2_wickets = 'N/A'
    team1_inngs2_overs = 'N/A'

# Extract Team 2 info
team2_id = match_data['matchInfo']['team2']['teamId']
team2_name = match_data['matchInfo']['team2']['teamName']

# Extract Team 2's scores with checks for missing keys
team2_inngs1_score = match_data['matchScore']['team2Score']['inngs1']
team2_inngs1_runs = team2_inngs1_score.get('runs', 'N/A')
team2_inngs1_wickets = team2_inngs1_score.get('wickets', 'Declared')
team2_inngs1_overs = team2_inngs1_score.get('overs', 'N/A')

team2_inngs2_score = match_data['matchScore']['team2Score'].get('inngs2')
if team2_inngs2_score:
    team2_inngs2_runs = team2_inngs2_score.get('runs', 'N/A')
    team2_inngs2_wickets = team2_inngs2_score.get('wickets', 'Declared')
    team2_inngs2_overs = team2_inngs2_score.get('overs', 'N/A')
else:
    team2_inngs2_runs = 'N/A'
    team2_inngs2_wickets = 'N/A'
    team2_inngs2_overs = 'N/A'    
# Print the match details
print(f"--- Cricket Match Details ---")
print(f"Match ID: {match_id}")
print(f"Description: {match_descriptions}")
print(f"Format: {match_format}")
print(f"Status: {match_status}")
print(f"Venue: {venue}")
print(f"")

print(f"--- Team 1: {team1_name} ---")
print(f"Team ID: {team1_id}")
print(f"  Innings 1: {team1_inngs1_runs}/{team1_inngs1_wickets} ({team1_inngs1_overs} Overs)")
print(f"  Innings 2: {team1_inngs2_runs}/{team1_inngs2_wickets} ({team1_inngs2_overs} Overs)")
print(f"")

print(f"--- Team 2: {team2_name} ---")
print(f"Team ID: {team2_id}")
print(f"  Innings 1: {team2_inngs1_runs}/{team2_inngs1_wickets} ({team2_inngs1_overs} Overs)")
print(f"  Innings 2: {team2_inngs2_runs}/{team2_inngs2_wickets} ({team2_inngs2_overs} Overs)")
print(f"")

--- Cricket Match Details ---
Match ID: 48002
Description: 1st Warm-up Match
Format: TEST
Status: Match drawn
Venue: County Ground

--- Team 1: SUSSEX ---
Team ID: 41
  Innings 1: 247/10 (79.1 Overs)
  Innings 2: N/A/N/A (N/A Overs)

--- Team 2: NEW ZEALAND ---
Team ID: 13
  Innings 1: 342/3 (90.0 Overs)
  Innings 2: 40/Declared (8.0 Overs)

In [ ]:
from db_connection import get_db_connection
from pymysql import Error

# Function to insert or update match details into the match_details table
def insert_match_details(connection, match_data_tuple):
    cursor = connection.cursor()
    # Using ON DUPLICATE KEY UPDATE to handle existing records gracefully
    insert_query = """
    INSERT INTO match_details (match_id, match_descr, match_format, status, venue, series_id)
    VALUES (%s, %s, %s, %s, %s, %s)
    ON DUPLICATE KEY UPDATE
        match_descr = VALUES(match_descr),
        match_format = VALUES(match_format),
        status = VALUES(status),
        venue = VALUES(venue),
        series_id = VALUES(series_id)
    """
    try:
        cursor.execute(insert_query, match_data_tuple)
        print(f"Match details for match ID {match_data_tuple[0]} inserted or updated successfully.")
    except Error as e:
        print(f"Error inserting match details for match ID {match_data_tuple[0]}: {e}")
        raise # Re-raise the exception to allow the main block to handle rollback

# Main script logic
if 'matchDetails' in data and isinstance(data['matchDetails'], list):
    matches = data['matchDetails']
    connection = get_db_connection()
    
    if connection:
        try:
            # Iterate through each match in the list `data['matchDetails']`
            for match_details_item in matches:
                if 'matchDetailsMap' in match_details_item and 'match' in match_details_item['matchDetailsMap']:
                    match_data = match_details_item['matchDetailsMap']['match'][0]
                    
                    series_id = match_data['matchInfo']['seriesId']
                    match_id = match_data['matchInfo']['matchId']
                    match_descriptions = match_data['matchInfo']['matchDesc']
                    match_format = match_data['matchInfo']['matchFormat']
                    match_status = match_data['matchInfo']['status']
                    venue = match_data['matchInfo']['venueInfo']['ground']
                    # Extract Team 1 info
                    team1_id = match_data['matchInfo']['team1']['teamId']
                    team1_name = match_data['matchInfo']['team1']['teamName']

                    # Extract Team 1's scores with checks for missing keys
                    team1_inngs1_score = match_data['matchScore']['team1Score']['inngs1']
                    team1_inngs1_runs = team1_inngs1_score.get('runs', 'N/A')
                    team1_inngs1_wickets = team1_inngs1_score.get('wickets', 'Declared')
                    team1_inngs1_overs = team1_inngs1_score.get('overs', 'N/A')

                    team1_inngs2_score = match_data['matchScore']['team1Score'].get('inngs2')
                    if team1_inngs2_score:
                        team1_inngs2_runs = team1_inngs2_score.get('runs', 'N/A')
                        team1_inngs2_wickets = team1_inngs2_score.get('wickets', 'Declared')
                        team1_inngs2_overs = team1_inngs2_score.get('overs', 'N/A')
                    else:
                        team1_inngs2_runs = 'N/A'
                        team1_inngs2_wickets = 'N/A'
                        team1_inngs2_overs = 'N/A'

                    # Extract Team 2 info
                    team2_id = match_data['matchInfo']['team2']['teamId']
                    team2_name = match_data['matchInfo']['team2']['teamName']

                    # Extract Team 2's scores with checks for missing keys
                    team2_inngs1_score = match_data['matchScore']['team2Score']['inngs1']
                    team2_inngs1_runs = team2_inngs1_score.get('runs', 'N/A')
                    team2_inngs1_wickets = team2_inngs1_score.get('wickets', 'Declared')
                    team2_inngs1_overs = team2_inngs1_score.get('overs', 'N/A')

                    team2_inngs2_score = match_data['matchScore']['team2Score'].get('inngs2')
                    if team2_inngs2_score:
                        team2_inngs2_runs = team2_inngs2_score.get('runs', 'N/A')
                        team2_inngs2_wickets = team2_inngs2_score.get('wickets', 'Declared')
                        team2_inngs2_overs = team2_inngs2_score.get('overs', 'N/A')
                    else:
                        team2_inngs2_runs = 'N/A'
                        team2_inngs2_wickets = 'N/A'
                        team2_inngs2_overs = 'N/A'    

                    match_data_tuple = (match_id, match_descriptions, match_format, match_status, venue, series_id)
                    
                    # Insert or update the details for the current match
                    insert_match_details(connection, match_data_tuple)
            
            # Commit the transaction after all matches have been processed
            connection.commit()
            print("All match details processed and committed.")

        except Error as e:
            print(f"Transaction failed: {e}. Rolling back changes.")
            connection.rollback() # Rollback all changes on error
        finally:
            connection.close() # Always close the connection
    else:
        print("Failed to connect to the database.")
else:
    print("Match data not found or is not a list in the specified structure.")

Match details for match ID 48002 inserted or updated successfully.
Match details for match ID 48009 inserted or updated successfully.
Match details for match ID 38326 inserted or updated successfully.
Match details for match ID 38331 inserted or updated successfully.
Match details for match ID 38332 inserted or updated successfully.
All match details processed and committed.

In [10]:
from db_connection import get_db_connection
from pymysql import Error

# Insert match details
def insert_match_details(connection, match_data_tuple):
    cursor = connection.cursor()
    insert_query = """
    INSERT INTO match_details (match_id, match_descr, match_format, status, venue, series_id)
    VALUES (%s, %s, %s, %s, %s, %s)
    ON DUPLICATE KEY UPDATE
        match_descr = VALUES(match_descr),
        match_format = VALUES(match_format),
        status = VALUES(status),
        venue = VALUES(venue),
        series_id = VALUES(series_id)
    """
    cursor.execute(insert_query, match_data_tuple)


# Insert team details
def insert_team(connection, team_data_tuple):
    cursor = connection.cursor()
    insert_query = """
    INSERT INTO teams (team_id, team_name, match_id)
    VALUES (%s, %s, %s)
    ON DUPLICATE KEY UPDATE
        team_name = VALUES(team_name)
    """
    cursor.execute(insert_query, team_data_tuple)


# Insert innings scores
def insert_innings_score(connection, innings_tuple):
    cursor = connection.cursor()
    insert_query = """
    INSERT INTO innings_scores (team_id, match_id, innings_number, runs, wickets, overs)
    VALUES (%s, %s, %s, %s, %s, %s)
    """
    cursor.execute(insert_query, innings_tuple)


# Main script
if 'matchDetails' in data and isinstance(data['matchDetails'], list):
    matches = data['matchDetails']
    connection = get_db_connection()

    if connection:
        try:
            for match_details_item in matches:
                if 'matchDetailsMap' in match_details_item and 'match' in match_details_item['matchDetailsMap']:
                    match_data = match_details_item['matchDetailsMap']['match'][0]

                    # --- Match details ---
                    match_id = match_data['matchInfo']['matchId']
                    series_id = match_data['matchInfo']['seriesId']
                    match_descr = match_data['matchInfo']['matchDesc']
                    match_format = match_data['matchInfo']['matchFormat']
                    match_status = match_data['matchInfo']['status']
                    venue = match_data['matchInfo']['venueInfo']['ground']

                    insert_match_details(connection, (match_id, match_descr, match_format, match_status, venue, series_id))

                    # --- Team 1 ---
                    team1_id = match_data['matchInfo']['team1']['teamId']
                    team1_name = match_data['matchInfo']['team1']['teamName']
                    insert_team(connection, (team1_id, team1_name, match_id))

                    team1_inngs1 = match_data['matchScore']['team1Score'].get('inngs1', {})
                    insert_innings_score(connection, (team1_id, match_id, 1,
                                                      team1_inngs1.get('runs', 'N/A'),
                                                      team1_inngs1.get('wickets', 'N/A'),
                                                      team1_inngs1.get('overs', 'N/A')))
                    
                    team1_inngs2 = match_data['matchScore']['team1Score'].get('inngs2')
                    if team1_inngs2:
                        insert_innings_score(connection, (team1_id, match_id, 2,
                                                          team1_inngs2.get('runs', 'N/A'),
                                                          team1_inngs2.get('wickets', 'N/A'),
                                                          team1_inngs2.get('overs', 'N/A')))

                    # --- Team 2 ---
                    team2_id = match_data['matchInfo']['team2']['teamId']
                    team2_name = match_data['matchInfo']['team2']['teamName']
                    insert_team(connection, (team2_id, team2_name, match_id))

                    team2_inngs1 = match_data['matchScore']['team2Score'].get('inngs1', {})
                    insert_innings_score(connection, (team2_id, match_id, 1,
                                                      team2_inngs1.get('runs', 'N/A'),
                                                      team2_inngs1.get('wickets', 'N/A'),
                                                      team2_inngs1.get('overs', 'N/A')))
                    
                    team2_inngs2 = match_data['matchScore']['team2Score'].get('inngs2')
                    if team2_inngs2:
                        insert_innings_score(connection, (team2_id, match_id, 2,
                                                          team2_inngs2.get('runs', 'N/A'),
                                                          team2_inngs2.get('wickets', 'N/A'),
                                                          team2_inngs2.get('overs', 'N/A')))

            # ✅ Commit after all inserts
            connection.commit()
            print("All match, team, and score details inserted successfully.")

        except Error as e:
            print(f"Transaction failed: {e}. Rolling back changes.")
            connection.rollback()
        finally:
            connection.close()
    else:
        print("Failed to connect to database.")
else:
    print("Match data not found or is not a list in the specified structure.")

All match, team, and score details inserted successfully.

In [11]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/trending"

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
data = response.json()

In [13]:
data.keys()

dict_keys(['player', 'category'])

In [17]:
# data['category']
data['player'][0].keys()

dict_keys(['id', 'name', 'teamName', 'faceImageId'])

In [24]:
player_details = data['player'][0]
player_id = player_details['id']
player_id
player_name = player_details['name']

team_name = player_details['teamName']
player_name

'Luka Woods'

In [25]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/search"

querystring = {"plrN":"Tucker"}

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()

In [27]:
data.keys()

dict_keys(['player', 'category'])

In [28]:
# data['category']
data['player'][0].keys()

dict_keys(['id', 'name', 'teamName', 'faceImageId', 'dob'])

In [29]:
player_details = data['player'][0]
player_id = player_details['id']
print(player_id)
player_name = player_details['name']
print(player_name)
team_name = player_details['teamName']
print(team_name)

674
Kwame Tucker
Bermuda

In [16]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/venues/v1/44"

headers = {
	"x-rapidapi-key": "05be0855e7msh0088c5d61d942a7p11ae06jsn2eac138a9d2c",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [17]:
data
# data.keys()

{'ground': 'McLean Park',
 'city': 'Napier',
 'country': 'New Zealand',
 'timezone': '+13:00',
 'established': 1911,
 'capacity': '22,500',
 'knownAs': 'McLean Park',
 'ends': 'Centennial Stand End, Embankment End',
 'homeTeam': 'Central Districts',
 'floodlights': True,
 'curator': 'Phil Stoyanoff ',
 'profile': "<b>Venue description:</b>\n\n Rugby and Cricket are the two major sports events held at Napier's McLean Park. Established in 1911, the stadium was built on the 10 acres of land donated by Sir Douglas in memory of his father, Sir Donald McLean, who was a local politician and a government official. 'Sir Donald McLean Park' was the official name of the ground, before it took its current name, 'McLean Park.' It is a square dimensional ground, covered by four stands and a huge grass bank behind the sightscreen at one end.\n\nLocated in Hawke's Bay on the eastern coast of the North Island, Napier is one of New Zealand's driest cities, because of which the square at McLean Park doesn't have the spice that other grounds in the country have. The pitch here is regarded as batting-friendly and it is generally considered to be a very good wicket for limited-overs cricket. In fact, it is one of the world's highest scoring grounds at present.\n\nA Test match between hosts New Zealand and Pakistan in 1979 was the first international cricket match to be played at this venue. Since then, the BlackCaps have featured in 9 Test matches, winning one, drawing six and losing two. Quite clearly, not a happy hunting ground for the hosts in the longest format of the game.\n\nFour years later, New Zealand and Sri Lanka locked horns with each other to open McLean Park's ODI account on March 19, 1983. Although enjoying a good run at the start, as years went by, oppositions found ways to tackle New Zealand's strategies at this ground and the BlackCaps have suffered quite a few setbacks in the last 10 years.\n\n<b>How does the pitch play?</b>\n\nMcLean Park is regarded as one of the most batting friendly wickets in the world. The wicket tends to slow up as the game progresses. \n\n<b>Interesting facts about McLean Park:</b>\n\nBrett Lee clocked 160.8kph on March 5, 2005, to record the fastest ball ever bowled by him.\n\nNew Zealand's first floodlit home fixture was played here in 1996. Ten years later, in 2006, the artificial lights were upgraded to meet the latest requirements.\n\nIn March 2009, a fungus, which prevented the growth of grass, forced the groundsmen to shift the 22 yards, ahead of India's 2nd Test match against New Zealand.\n\nBy <b>MS Ramakrishnan</b>",
 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/44.jpg',
 'otherSports': 'Rugby',
 'imageId': '189174'}

In [6]:
venue_name = data['ground']
city = data['city']
country = data['country']
capacity = data['capacity']
data

{'ground': 'Basin Reserve',
 'city': 'Wellington',
 'country': 'New Zealand',
 'timezone': '+13:00',
 'capacity': '11,600',
 'ends': 'Vance Stand End, Scoreboard End',
 'homeTeam': 'Wellington',
 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/45.jpg',
 'imageId': '189174'}

In [ ]:
import requests
from db_connection import get_db_connection
from pymysql import Error

# Function to insert venue data into the MySQL table
def insert_venue_data(connection, venue_data):
    cursor = connection.cursor()

    insert_query = """
    INSERT INTO venues (venue_name, city, country, capacity)
    VALUES (%s, %s, %s, %s)
    ON DUPLICATE KEY UPDATE 
        city = VALUES(city),
        country = VALUES(country),
        capacity = VALUES(capacity)
    """
    
    try:
        cursor.execute(insert_query, venue_data)
        connection.commit()
        print(f"Venue inserted/updated successfully: {venue_data[0]}")
    except Error as e:
        print(f"Error while inserting venue data: {e}")
        connection.rollback()


# Function to fetch and insert venue data by venue_id
def process_venue(venue_id, api_key):
    url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{venue_id}"

    headers = {
        "x-rapidapi-key": api_key,
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json()
    else:
        print(f"Failed to fetch venue_id {venue_id}. Status code: {response.status_code}")
        return

    if data:
        connection = get_db_connection()
        if connection:
            venue_name = data.get("ground")
            city = data.get("city")
            country = data.get("country")

            # Clean capacity (remove commas → int)
            raw_capacity = data.get("capacity", "0")
            try:
                capacity = int(raw_capacity.replace(",", "")) if raw_capacity else 0
            except ValueError:
                capacity = 0

            venue_data = (venue_name, city, country, capacity)

            insert_venue_data(connection, venue_data)

            connection.close()
        else:
            print("Failed to connect to the database.")
    else:
        print(f"No data found for venue_id {venue_id}")


# 🚀 Main loop to process multiple venues
if __name__ == "__main__":
    api_key = "4023e3f131msh62f2c03a28eb631p17f1d0jsnce44030e0103"
    
    start_id = 21  # 👈 set your starting venue_id
    end_id = 40    # 👈 set your ending venue_id

    for venue_id in range(start_id, end_id + 1):
        process_venue(venue_id, api_key)

Venue inserted/updated successfully: Edgbaston
Failed to fetch venue_id 21. Status code: 429
Failed to fetch venue_id 22. Status code: 429
Failed to fetch venue_id 23. Status code: 429
Failed to fetch venue_id 24. Status code: 429
Failed to fetch venue_id 25. Status code: 429
Failed to fetch venue_id 26. Status code: 429
Failed to fetch venue_id 27. Status code: 429
Failed to fetch venue_id 28. Status code: 429
Failed to fetch venue_id 29. Status code: 429
Failed to fetch venue_id 30. Status code: 429
Failed to fetch venue_id 31. Status code: 429
Failed to fetch venue_id 32. Status code: 429
Failed to fetch venue_id 33. Status code: 429
Failed to fetch venue_id 34. Status code: 429
Failed to fetch venue_id 35. Status code: 429
Failed to fetch venue_id 36. Status code: 429
Failed to fetch venue_id 37. Status code: 429
Failed to fetch venue_id 38. Status code: 429
Failed to fetch venue_id 39. Status code: 429
Failed to fetch venue_id 40. Status code: 429